{
	"id": 77762950,
	"body": "Yes, I tried to bypass it, same error.\r\n\r\n\tiridium:go$ git push origin HEAD:refs/for/master\r\n\tCounting objects: 71, done.\r\n\tDelta compression using up to 4 threads.\r\n\tCompressing objects: 100% (23/23), done.\r\n\tWriting objects: 100% (23/23), 2.76 KiB | 0 bytes/s, done.\r\n\tTotal 23 (delta 15), reused 0 (delta 0)\r\n\tremote: Resolving deltas: 100% (15/15)\r\n\tremote: Processing changes: refs: 1, done    \r\n\tremote: (W) No changes between prior commit ffcc30e and new commit 4430bdf\r\n\tTo https://go.googlesource.com/go\r\n\t ! [remote rejected] HEAD -\u003e refs/for/master (no changes made)\r\n\terror: failed to push some refs to 'https://go.googlesource.com/go'\r\n\tiridium:go$ \r\n",
	"user": {
		"login": "4ad",
		"id": 1331747,
		"type": "User",
		"site_admin": false
	},
	"created_at": "2015-03-08T17:29:19Z",
	"updated_at": "2015-03-08T17:29:19Z"
}
