{
	"id": 144700087,
	"number": 15029,
	"state": "closed",
	"title": "cmd/compile: spooky compilation failure",
	"body": "https://go-review.googlesource.com/#/c/21333/\r\n\r\nWhen I try testing that CL, I get:\r\n\r\n    $ go run run.go\r\n    # go run run.go -- fixedbugs/bug278.go\r\n\r\n    bug278.go:21: missing error \"cannot|invalid\"\r\n    bug278.go:22: missing error \"cannot|invalid\"\r\n\r\n    FAIL\tfixedbugs/bug278.go\t0.081s\r\n    # go run run.go -- fixedbugs/issue8183.go\r\n\r\n    issue8183.go:21: missing error \"const initializer len\\\\(composite literal\\\\) is not a constant\"\r\n    issue8183.go:22: missing error \"array bound must be non-negative\"\r\n    issue8183.go:22: missing error \"const initializer len\\\\(composite literal\\\\) is not a constant\"\r\n\r\n    FAIL\tfixedbugs/issue8183.go\t0.075s\r\n    exit status 1\r\n\r\nI don't see how that's possible.  Either the compiler should have panicked because at some point `t == nil`, or the behavior should have been identical.\r\n\r\n/cc @randall77 @josharian ",
	"user": {
		"login": "mdempsky",
		"id": 38349,
		"type": "User",
		"site_admin": false
	},
	"comments": 4,
	"closed_at": "2016-03-30T20:44:37Z",
	"created_at": "2016-03-30T19:43:40Z",
	"updated_at": "2016-03-31T18:00:26Z"
}
