{
	"id": 252792007,
	"body": "@ianlancetaylor, @spenczar,\r\nI modified the example a little, by also deferring the inner F() calling.\r\nBut the recover calling in this F still returns nil.\r\nThe 3 conditions described in spec don't cover this condition.\r\n\r\n\tpackage main\r\n\r\n\timport \"fmt\"\r\n\r\n\tfunc F() {\r\n\t\tfmt.Println(recover())\r\n\t}\r\n\r\n\tfunc G() {\r\n\t\tdefer F()\r\n\t\tpanic(1)\r\n\t}\r\n\r\n\tfunc H() {\r\n\t\tdefer func() {\r\n\t\t\tdefer F() // I modified this line\r\n\t\t}()\r\n\t\tpanic(2)\r\n\t}\r\n\r\n\tfunc main() {\r\n\t\tfmt.Print(\"G(): \")\r\n\t\tG()\r\n\t\tfmt.Print(\"H(): \")\r\n\t\tH()\r\n\t}\r\n",
	"user": {
		"login": "golang101",
		"id": 22589241,
		"type": "User",
		"site_admin": false
	},
	"created_at": "2016-10-11T02:02:05Z",
	"updated_at": "2016-10-11T02:02:59Z"
}
