{
	"id": 199246351,
	"body": "I've looked at the builder history and noticed a few cases where\r\nsimilar errors in cmd/link happened when running the tests.\r\n\r\nI think this issue in another consequence of the same issue.\r\n\r\nFor example, on 2016-02-29:\r\n\r\n```\r\n--- FAIL: TestIssue6480 (0.30s)\r\n\tgo_test.go:244: running testgo [test -c -test.bench=XXX errors]\r\n\tgo_test.go:263: standard error:\r\n\tgo_test.go:264: # testmain\r\n\t\t2016/02/29 00:23:46 -5894 out of range for uint8\r\n\t\tpanic: -5894 out of range for uint8\r\n\t\t\r\n\t\tgoroutine 1 [running]:\r\n\t\tpanic(0x3ec960, 0x99f6cc0)\r\n\t\t\t/tmp/gobuilder/plan9-amd64-9front-75cc05fa557b/go/src/runtime/panic.go:483 +0x3fd\r\n\t\tlog.Panicf(0x493bc0, 0x19, 0x91f0c68, 0x1, 0x1)\r\n\t\t\t/tmp/gobuilder/plan9-amd64-9front-75cc05fa557b/go/src/log/log.go:327 +0xdd\r\n\t\tcmd/link/internal/ld.rduint8(0x8cba120, 0x24)\r\n\t\t\t/tmp/gobuilder/plan9-amd64-9front-75cc05fa557b/go/src/cmd/link/internal/ld/objfile.go:422 +0xfa\r\n\t\tcmd/link/internal/ld.readsym(0x88b0240, 0x8cba120, 0x8c32aca, 0x4, 0x9368460, 0x50)\r\n\t\t\t/tmp/gobuilder/plan9-amd64-9front-75cc05fa557b/go/src/cmd/link/internal/ld/objfile.go:245 +0xccd\r\n\t\tcmd/link/internal/ld.ldobjfile(0x88b0240, 0x8cba120, 0x8c32aca, 0x4, 0x725ba, 0x9368460, 0x50)\r\n\t\t\t/tmp/gobuilder/plan9-amd64-9front-75cc05fa557b/go/src/cmd/link/internal/ld/objfile.go:147 +0xa67\r\n\t\tcmd/link/internal/ld.ldobj(0x8cba120, 0x8c32aca, 0x4, 0x72627, 0x9368460, 0x50, 0x93fb180, 0x48, 0x1, 0x0)\r\n\t\t\t/tmp/gobuilder/plan9-amd64-9front-75cc05fa557b/go/src/cmd/link/internal/ld/lib.go:1339 +0x155f\r\n\t\tcmd/link/internal/ld.objfile(0x941a2a0)\r\n\t\t\t/tmp/gobuilder/plan9-amd64-9front-75cc05fa557b/go/src/cmd/link/internal/ld/lib.go:835 +0xee0\r\n\t\tcmd/link/internal/ld.loadlib()\r\n\t\t\t/tmp/gobuilder/plan9-amd64-9front-75cc05fa557b/go/src/cmd/link/internal/ld/lib.go:510 +0x5cb\r\n\t\tcmd/link/internal/ld.Ldmain()\r\n\t\t\t/tmp/gobuilder/plan9-amd64-9front-75cc05fa557b/go/src/cmd/link/internal/ld/pobj.go:187 +0x162c\r\n\t\tcmd/link/internal/amd64.Main()\r\n\t\t\t/tmp/gobuilder/plan9-amd64-9front-75cc05fa557b/go/src/cmd/link/internal/amd64/obj.go:44 +0x1e\r\n\t\tmain.main()\r\n\t\t\t/tmp/gobuilder/plan9-amd64-9front-75cc05fa557b/go/src/cmd/link/main.go:27 +0x374\r\n\t\t\r\n\tgo_test.go:273: go [test -c -test.bench=XXX errors] failed unexpectedly: exit status: 'testgo 292097: 2'\r\nFAIL\r\nFAIL\tcmd/go\t43.226s\r\n```\r\n\r\nWhere [src/cmd/link/internal/ld/objfile.go:245](https://github.com/golang/go/blob/75cc05f/src/cmd/link/internal/ld/objfile.go#L245) is:\r\n\r\n```\r\nr.Siz = rduint8(f)\r\n```\r\n\r\nSee http://build.golang.org/log/b6a6656739598fd705fc25bab896f998bb3db8b4",
	"user": {
		"login": "0intro",
		"id": 6043744,
		"type": "User",
		"site_admin": false
	},
	"created_at": "2016-03-21T12:14:17Z",
	"updated_at": "2016-03-21T12:14:17Z"
}
