{
	"id": 61366944,
	"number": 10162,
	"state": "closed",
	"title": "runtime: TestRaiseException fails on windows server 2003 (amd64)",
	"body": "This program:\r\n```\r\npackage main\r\nimport \"syscall\"\r\nfunc main() {\r\n        const EXCEPTION_NONCONTINUABLE = 1\r\n        mod := syscall.MustLoadDLL(\"kernel32.dll\")\r\n        proc := mod.MustFindProc(\"RaiseException\")\r\n        proc.Call(0xbad, EXCEPTION_NONCONTINUABLE, 0, 0)\r\n        println(\"RaiseException should not return\")\r\n}\r\n```\r\n\r\nwhen running standalone, doesn't output anything on windows server 2003.\r\nhowever, when running inside gdb, it correct output unexpected signal during cgo execution\r\nmessage.\r\n\r\nMoreover, if I add a println statement before proc.Call, the program will also be working\r\nas intended when running standalone.\r\n\r\n/cc @alexbrainman ",
	"user": {
		"login": "minux",
		"id": 135652,
		"type": "User",
		"site_admin": false
	},
	"labels": [
		{
			"name": "FrozenDueToAge"
		}
	],
	"comments": 8,
	"closed_at": "2015-03-30T03:39:12Z",
	"created_at": "2015-03-14T02:42:50Z",
	"updated_at": "2016-06-25T02:03:16Z",
	"milestone": {
		"id": 905105,
		"number": 1,
		"title": "Go1.5"
	}
}
