{
	"id": 67246795,
	"body": "Your repro does not check for a possible error on Open\r\nOn 17 Dec 2014 09:39, \"azdagron\" \u003cnotifications@github.com\u003e wrote:\r\n\r\n\u003e OS: Windows 7 64-bit\r\n\u003e GCC version: gcc (x86_64-posix-seh-rev1, Built by MinGW-W64 project) 4.9.1\r\n\u003e Go version: 1.4 (but also happens on 1.2+, didn't check \u003c 1.2)\r\n\u003e\r\n\u003e Description:\r\n\u003e when the below program is compiled and run, the go program either panics\r\n\u003e or crashes outright.\r\n\u003e\r\n\u003e We did some spelunking and from what we can tell, the crash happens when\r\n\u003e sqlite3 tries to call a kernel32.dll function from its aSyscall array. The\r\n\u003e function pointer is supposed to point to an import jump table, but instead\r\n\u003e points to a page close to the jump table that has some garbage in it.\r\n\u003e Sampling other function pointers in the aSyscall array show they properly\r\n\u003e go the the import jump table.\r\n\u003e\r\n\u003e We've used github.com/mattn/go-sqlite3 for quite a while with no issues.\r\n\u003e We made some unrelated changes and recompiled our application and suddenly\r\n\u003e hit the issue. Recompiling the program without the changes stopped\r\n\u003e triggering the bug, but once we found the issue we've been able to hit it\r\n\u003e with smaller programs (see the program below)\r\n\u003e\r\n\u003e We suspect a linker issue, which is why we reported it here.\r\n\u003e\r\n\u003e Repro instructions:\r\n\u003e 1) go get github.com/mattn/go-sqlite3\r\n\u003e 2) compile the following go program:\r\n\u003e\r\n\u003e package main\r\n\u003e\r\n\u003e import (\r\n\u003e     \"database/sql\"\r\n\u003e\r\n\u003e     _ \"github.com/mattn/go-sqlite3\"\r\n\u003e )\r\n\u003e\r\n\u003e func main() {\r\n\u003e     db, err := sql.Open(\"sqlite3\", \"foo.db\")\r\n\u003e     rows, err := db.Query(\".tables;\")\r\n\u003e     if err == nil {\r\n\u003e         rows.Close()\r\n\u003e     }\r\n\u003e     db.Close()\r\n\u003e }\r\n\u003e\r\n\u003e An example of the output:\r\n\u003e\r\n\u003e Exception 0xc0000005 0x8 0x646138 0x646138\r\n\u003e PC=0x646138\r\n\u003e signal arrived during cgo execution\r\n\u003e github.com/mattn/go-sqlite3._Cfunc_sqlite3_close_v2(0x8966b8, 0xc000000000)\r\n\u003e         github.com/mattn/go-sqlite3/_obj/_cgo_gotypes.go:182 +0x4agithub.com/mattn/go-sqlite3.(*SQLiteConn).Close(0xc08204a018, 0x0, 0x0)\r\n\u003e         c:/work/repro/src/github.com/mattn/go-sqlite3/sqlite3.go:320 +0x44\r\n\u003e database/sql.(*driverConn).finalClose(0xc08200e1e0, 0x0, 0x0)\r\n\u003e         c:/go/src/database/sql/sql.go:322 +0x125\r\n\u003e database/sql.finalCloser.(database/sql.finalClose)┬╖fm(0x0, 0x0)\r\n\u003e         c:/go/src/database/sql/sql.go:410 +0x52\r\n\u003e database/sql.(*DB).Close(0xc082032000, 0x0, 0x0)\r\n\u003e         c:/go/src/database/sql/sql.go:493 +0x3c2\r\n\u003e main.main()\r\n\u003e         c:/work/repro/src/repro/main.go:15 +0xdd\r\n\u003e\r\n\u003e goroutine 17 [syscall, locked to thread]:\r\n\u003e runtime.goexit()\r\n\u003e         c:/go/src/runtime/asm_amd64.s:2232 +0x1\r\n\u003e rax     0x0\r\n\u003e rbx     0x3\r\n\u003e rcx     0x78\r\n\u003e rdx     0x0\r\n\u003e rdi     0x896ba8\r\n\u003e rsi     0x897560\r\n\u003e rbp     0x896970\r\n\u003e rsp     0x22fce8\r\n\u003e r8      0x5db0c0\r\n\u003e r9      0x896ba8\r\n\u003e r10     0x18\r\n\u003e r11     0x5754e0\r\n\u003e r12     0x0\r\n\u003e r13     0x0\r\n\u003e r14     0x0\r\n\u003e r15     0x0\r\n\u003e rip     0x646138\r\n\u003e rflags  0x10206\r\n\u003e cs      0x33\r\n\u003e fs      0x53\r\n\u003e gs      0x2b\r\n\u003e\r\n\u003e —\r\n\u003e Reply to this email directly or view it on GitHub\r\n\u003e \u003chttps://github.com/golang/go/issues/9356\u003e.\r\n\u003e",
	"user": {
		"login": "davecheney",
		"id": 7171,
		"type": "User",
		"site_admin": false
	},
	"created_at": "2014-12-16T22:42:40Z",
	"updated_at": "2014-12-16T22:42:40Z"
}
