{
	"id": 67121583,
	"body": "This is GitHub misbehaving. They don't want to aid discovery of private repos, so they return auth challenges instead of a 404. Not sure of the best move here.",
	"user": {
		"login": "adg",
		"id": 8446613,
		"type": "User",
		"site_admin": false
	},
	"created_at": "2014-12-16T07:20:21Z",
	"updated_at": "2014-12-16T07:20:21Z"
}
