{
	"id": 66056058,
	"body": "\u003ca id=\"c9\"\u003e\u003c/a\u003eComment 9:\n\n\u003cpre\u003eAlex, are you sure? What is the new error message? (if it changed)\n\nI had to use a different array size in my tests (because with 28*100 it didn't panic for\nme, had to use ~32*100), and I specifically checked with different array sizes that it\npaniced before the change and didn't after the change.\n\nEven more, I made a script to test a range of array sizes for stack error. With my patch\nI cannot find any range that would fail. If I backout the fix then go fails for array\nsizes 3029-3888. It's clear that my patch fixes your test case. Can you run it and\nconfirm that you still get failures?\n\n(it takes a lot of time to complete, though, because it's Windows after all)\u003c/pre\u003e\n\n\n\n\n\nAttachments:\n\n1. \u003ca href=\"https://storage.googleapis.com/go-attachment/1779/9/go-test-array.py\"\u003ego-test-array.py\u003c/a\u003e (1640 bytes)",
	"user": {
		"login": "snaury",
		"id": 53117,
		"type": "User",
		"site_admin": false
	},
	"created_at": "2011-05-17T06:54:35Z",
	"updated_at": "2014-12-08T10:09:52Z"
}
