{
	"id": 51281326,
	"number": 3899,
	"state": "closed",
	"title": "unexpected fault address when passing function value",
	"body": "\u003cpre\u003eRunning go1.0.2 on Ubuntu 12.04 i386, the program\n\npackage main\n\nfunc bar(f func()) {\n\tf()\n}\n\nfunc foo() {\n\tf := func() {}\n\tif f == nil {}\n\tbar(f)\n}\n\nfunc main() {\n\tfoo()\n}\n\nproduces the output\n\nunexpected fault address 0x8048ca2\nthrow: fault\n[signal 0xb code=0x2 addr=0x8048ca2 pc=0x8050f3d]\n\ngoroutine 1 [running]:\nmain.bar(0x8050f0e, 0x8050f0e)\n\t/home/gordon/src/go/src/fault.go:4 +0x20\nmain.foo()\n\t/home/gordon/src/go/src/fault.go:10 +0x31\nmain.main()\n\t/home/gordon/src/go/src/fault.go:14 +0x1c\n\ngoroutine 2 [syscall]:\ncreated by runtime.main\n\t/usr/local/go/src/pkg/runtime/proc.c:221\nexit status 2\n\nIn the process of whittling my program down to find the core problem, the output varied\namong this, \u0026quot;invalid m state in scheduler\u0026quot;, and SIGILL.\n\nStrangely, removing \u0026quot;if f == nil {}\u0026quot; or adding print(f) causes the problem to\ngo away.\u003c/pre\u003e",
	"user": {
		"login": "gordonklaus",
		"id": 1638352,
		"type": "User",
		"site_admin": false
	},
	"labels": [
		{
			"name": "FrozenDueToAge"
		}
	],
	"comments": 5,
	"closed_at": "2014-12-08T10:20:38Z",
	"created_at": "2012-08-03T07:22:35Z",
	"updated_at": "2016-06-24T22:22:28Z"
}
